config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  root 'main#index'

  get '/filter' => 'main#filter'
  get '/oauth/s5' => 'main#s5'
  get '/logout' => 'users#logout'
  get '/hall_of_fame' => 'main#hall_of_fame'

  get '/error' => 'main#intentional_error'

  scope 'teams', as: 'teams' do
    get '/mine' => 'teams#code'
    post '/mine' => 'teams#user_update'
    get '/join' => 'teams#join'
    get '/join/:code' => 'teams#join_link', as: 'join_link'
    post '/join' => 'teams#join_team'
    get '/leave' => 'teams#leave'
    post '/project' => 'teams#save_project'
  end

  get '/teams/batch/:batch_id/event/:id' => 'teams#event', as: 'event'
  get '/teams/batch/:id' => 'teams#batch', as: 'batch'

  scope 'login', as: 'login' do
    get '/' => 'users#login'
    get '/s5' => 'users#s5_login'
    post '/' => 'users#post_login'
    get '/manual' => 'main#manual_login', as: 'manual'
    post '/manual' => 'main#manual_login'
  end

  scope 'register', as: 'register' do
    get '/' => 'users#register'
    post '/' => 'users#post_register'
  end

  scope 'api', as: 'api' do
    get '/me' => 'users#api_me'
    get '/exchange' => 'main#exchange_token'
    post '/slack/:id' => 'main#slack_hook', as: 'slack_hook'
  end

  scope 'legacy', as: 'legacy' do
    get '/' => 'main#legacy'
    get '/oauth' => 'main#legacy_oauth'
  end

  namespace :judge do
    root 'main#index'
    resources :awards
    post '/awards/:id' => 'awards#update'
  end

  namespace :volunteer do
    root 'main#index'
    resources :awards
    resources :teams
    post '/awards/:id' => 'awards#update'
  end

  namespace :admin do
    root 'main#index'
    get '/set_batch/:id' => 'main#set_batch', as: 'set_batch'
    get '/set_event/:id' => 'main#set_event', as: 'set_event'
    get '/event' => 'main#event', as: 'event'
    get '/batch' => 'main#batch', as: 'batch'
    get '/awards' => 'main#awards', as: 'awards'
    get '/awards/seed' => 'main#seed_awards', as: 'seed_awards'
    get '/scramble' => 'main#scramble', as: 'scramble'
    post '/inject' => 'main#inject', as: 'inject'
  end

  namespace :integration do
    root 'main#index'
    get '/slack' => 'slack#index'
    patch '/slack' => 'slack#update_token'
  end

  resources :teams
  resources :users

end

app/views/admin/_buttons.html.erb
<div class="section group">
  <div class="col span_1_of_4">
    <a href="<%= admin_event_path %>" class="admin-button admin-button-blue">
      <div class="admin-button-title">EVENT</div>
      <% if current_user.event %>
        <div class="admin-button-subtext"><%= current_user.event.city %></div>
      <% else %>
        <div class="admin-button-subtext">None</div>
      <% end %>
    </a>
  </div>
  <div class="col span_1_of_4">
    <a href="<%= admin_batch_path %>" class="admin-button admin-button-red">
      <div class="admin-button-title">BATCH</div>
      <div class="admin-button-subtext"><%= current_batch.name %></div>
    </a>
  </div>
  <div class="col span_1_of_4">
    <a href="<%= admin_awards_path %>" class="admin-button admin-button-green">
      <div class="admin-button-title">AWARDS</div>
      <% if current_batch.awards_shown %>
        <div class="admin-button-subtext">Shown</div>
      <% else %>
        <div class="admin-button-subtext">Hidden</div>
      <% end %>
    </a>
  </div>
  <div class="col span_1_of_4">
    <a href="<%= admin_scramble_path %>"  class="admin-button admin-button-orange">
      <div class="admin-button-title">SCRAMBLE</div>
      <div class="admin-button-subtext">Scramble Teams</div>
    </a>
  </div>
</div><br>