config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  root 'main#index'

  get '/filter' => 'main#filter'
  get '/oauth/s5' => 'main#s5'
  get '/logout' => 'users#logout'
  get '/hall_of_fame' => 'main#hall_of_fame'

  get '/error' => 'main#intentional_error'

  scope 'teams', as: 'teams' do
    get '/mine' => 'teams#code'
    post '/mine' => 'teams#user_update'
    get '/join' => 'teams#join'
    get '/join/:code' => 'teams#join_link', as: 'join_link'
    post '/join' => 'teams#join_team'
    get '/leave' => 'teams#leave'
    post '/project' => 'teams#save_project'
  end

  get '/teams/batch/:batch_id/event/:id' => 'teams#event', as: 'event'
  get '/teams/batch/:id' => 'teams#batch', as: 'batch'

  scope 'login', as: 'login' do
    get '/' => 'users#login'
    get '/s5' => 'users#s5_login'
    post '/' => 'users#post_login'
    get '/manual' => 'main#manual_login', as: 'manual'
    post '/manual' => 'main#manual_login'
  end

  scope 'register', as: 'register' do
    get '/' => 'users#register'
    post '/' => 'users#post_register'
  end

  scope 'api', as: 'api' do
    get '/me' => 'users#api_me'
    get '/exchange' => 'main#exchange_token'
    post '/slack/:id' => 'main#slack_hook', as: 'slack_hook'
  end

  scope 'legacy', as: 'legacy' do
    get '/' => 'main#legacy'
    get '/oauth' => 'main#legacy_oauth'
  end

  namespace :judge do
    root 'main#index'
    resources :awards
    post '/awards/:id' => 'awards#update'
  end

  namespace :volunteer do
    root 'main#index'
    resources :awards
    resources :teams
    post '/awards/:id' => 'awards#update'
  end

  namespace :admin do
    root 'main#index'
    get '/set_batch/:id' => 'main#set_batch', as: 'set_batch'
    get '/set_event/:id' => 'main#set_event', as: 'set_event'
    get '/event' => 'main#event', as: 'event'
    get '/batch' => 'main#batch', as: 'batch'
    get '/awards' => 'main#awards', as: 'awards'
    get '/awards/seed' => 'main#seed_awards', as: 'seed_awards'
    get '/scramble' => 'main#scramble', as: 'scramble'
    post '/inject' => 'main#inject', as: 'inject'
  end

  namespace :integration do
    root 'main#index'
    get '/slack' => 'slack#index'
    patch '/slack' => 'slack#update_token'
  end

  resources :teams
  resources :users

end

app/models/team.rb
class Team < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_and_belongs_to_many :tags
	has_many :awards
	belongs_to :batch
	belongs_to :event

	validates :name, :presence => true, :length => { maximum: 25 }
	validates :short_description, :presence => true, :length => { maximum: 75 }
	# validates_url_format_of :youtube_url
	validates :event_id, :presence => true
	# validates :slack_webhook_url, :format => {:with => URI.regexp}

	def team_photo
		if self.team_photo_url && self.team_photo_url != ""
			self.team_photo_url
		else
			"http://cdn.pcwallart.com/images/gradient-background-wallpaper-4.jpg" # TODO host locally
		end
	end

	def tags_as_hashtags
		hashtags = ""

		self.tags.each do |tag|
			hashtags += "\##{tag.as_hashtag} "
		end

		hashtags
	end

	def extra_rendered
		$markdown.render(self.extra || "")
	end

	def description_rendered
		$markdown.render(self.project_description)
	end

	def api_filter
		{
			:id => self.id,
			:name => self.name,
			:event => self.event.api_filter
		}
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	def index
		@title = "Current Teams"
		@batch = current_batch
	end

	def batch
		@batch = Batch.find(params[:id])
		@title = "Teams for #{@batch.name}"
		render :index
	end

	def edit
		unless current_user.admin then redirect_to root_path end
		@team = Team.find(params[:id])
		@title = "Edit #{@team.name}"
	end

	def update
		unless current_user.admin then redirect_to root_path end
		Team.find(params[:id]).update(:extra => params[:team][:extra], :team_photo_url => params[:team][:team_photo_url])
		redirect_to Team.find(params[:id])
	end

	def user_update
		if current_user_team
			team = current_user_team
			team.update(params.require(:team).permit(:name, :is_presenting, :short_description, :project_description, :youtube_url, :download_url, :website_url, tag_ids: []))

			if team.errors.any?
				flash[:error] = handle_errors(team.errors.full_messages)
			else
				flash[:message] = "Team updated"
			end

			redirect_to teams_mine_path
		else
			flash[:error] = "You don't have a team yet!"
			redirect_to root_path
		end
	end

	def show
		@team = Team.find(params[:id])
		@title = @team.name
		@extra_body_class = "full-content-width"

		@open_graph[:title] = @team.name
		@open_graph[:type] = "website"
		@open_graph[:url] = team_url(@team)
		@open_graph[:image] = @team.team_photo
		@open_graph[:description] = "#{@team.short_description} #{@team.tags_as_hashtags}"

		@twitter_card[:card] = "summary_large_image"
		@twitter_card[:title] = @team.name
		@twitter_card[:description] = "#{@team.short_description} #{@team.tags_as_hashtags}"
		@twitter_card[:image] = @team.team_photo
		@twitter_card["image:alt"] = "A photo of the CodeDay team that created #{@team.name}"
	end

	def code
		@title = "My Team"
		unless current_user_team then redirect_to root_path end
		@team = current_user_team
	end

	def join
		@title = "Join Team"
		if current_user_team
			redirect_to root_path
		end
	end

	def join_team
		if Team.where(:code => params[:team][:code], :batch => current_batch).exists?
			team = Team.where(:code => params[:team][:code]).first
			team.users << current_user
			redirect_to root_path
		else
			flash[:error] = "Could not find team for #{current_batch.name} with that code!"
			redirect_to teams_join_path
		end
	end

	def join_link
		unless current_user
			redirect_to login_s5_path
		else
			if current_user_team
				flash[:error] = "You already have a team!"
				redirect_to teams_mine_path
			else
				if Team.where(:code => params[:code], :batch => current_batch).exists?
					team = Team.where(:code => params[:team][:code]).first
					team.users << current_user
					redirect_to root_path
				else
					flash[:error] = "Could not find team for #{current_batch.name} with that code!"
					redirect_to teams_join_path
				end
			end
		end
	end

	def new
		@title = "Create Team"
		if current_user_team
			redirect_to root_path
		end
	end

	def create
		@title = "Create Team"
		if current_user_team
			redirect_to root_path
		end
		params.require(:team).permit(:name, :short_description, :event_id)
		if Event.where(:id => params[:team][:event_id]).first.is_a? Event
			team = Team.create(:name => params[:team][:name], :code => SecureRandom.urlsafe_base64(5), :event_id => params[:team][:event_id], :short_description => params[:team][:short_description], :batch_id => current_batch.id)
			if team.valid?
				team.users << current_user
				redirect_to teams_mine_path
			else
				flash[:error] = handle_errors(team.errors.full_messages)
				redirect_to new_team_path
			end
		else
			flash[:error] = "Invalid event"
			redirect_to new_team_path
		end
	end

	def event
		@teams = Team.where(:event_id => params[:id], :batch_id => params[:batch_id] || 1)
		respond_to do |m|
			m.json {
				json_teams = []
				@teams.each do |t|
					json_teams.push(t.api_filter)
				end
				render json: api_success({:teams => json_teams})
			}

			m.html {
				@event = Event.find(params[:id])
				@title = "Teams for #{@event.city}"
				@batch = Batch.find(params[:batch_id] || 1)
			}
		end
	end

	def leave
		team = current_user.current_team
		team.users.delete(current_user)
		if team.users.count == 0
			team.destroy
		end
		redirect_to root_path
	end

	def save_project
		# params.require(:project).permit(:name, :description)
		# current_user_team.update(:project => params[:project][:name], :project_description => params[:project][:description])
		# render json: api_success
	end

	private
		def team_params
			params.require(:team).permit(:name, :event_id)
		end
end

app/controllers/volunteer/awards_controller.rb
class Volunteer::AwardsController < Volunteer::MainController
  def index
    @title = "Awards"
    @awards = Award.where(:event => current_user.event)
  end
end

app/controllers/volunteer/main_controller.rb
class Volunteer::MainController < ApplicationController
  before_filter :requires_volunteer

  def index
    @title = "Volunteer"
  end

  private
    def requires_volunteer
      if current_user && current_user.volunteer
        true
      else
        redirect_to root_path
      end
    end
end

app/controllers/volunteer/teams_controller.rb
class Volunteer::TeamsController < Volunteer::MainController
  def index
    @title = "Teams"
    @teams = Team.where(:event => current_user.event, :batch => current_batch)
  end

  def edit
    # this nice WHERE query lets us not do a bunch of validation afterwards...
    @team = Team.where(:event => current_user.event, :batch => current_batch).find(params[:id])
    @title = "Edit Team \"#{@team.name}\""
  end

  def update
    team = Team.where(:event => current_user.event, :batch => current_batch).find(params[:id])
    team.update(params.require(:team).permit(:name, :short_description, :project_description, :youtube_url, :download_url, :website_url, :team_photo_url, tag_ids: []))
    redirect_to volunteer_teams_path
  end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/volunteer/awards_helper.rb
module Volunteer::AwardsHelper
end

app/helpers/volunteer/main_helper.rb
module Volunteer::MainHelper
end

app/helpers/volunteer/teams_helper.rb
module Volunteer::TeamsHelper
end

app/views/volunteer/teams/edit.html.erb
<h2>Edit Team "<%= @team.name %>"</h2>

<%= form_for :team, method: "patch", url: volunteer_team_path(@team) do |form| %>
	<h2>Basic Info</h2>

	<p>
		<%= form.label :name, "Project name" %>
		<%= form.text_field :name, placeholder: "Industry Revolutionizer", required: true, maxlength: 25 %>
	</p>

	<p>
		<%= form.label :short_description, "Short description" %>
		<%= form.text_field :short_description, placeholder: "Our project revolutionizes the industry industry by creating industries.", required: true, maxlength: 75 %>
	</p>

	<h2>Extra Info</h2>

	<h3>Tags</h3>

	<p class="label-no-full-width">
		<%= form.collection_check_boxes(:tag_ids, Tag.all, :id, :text) do |tag| %>
			<%= tag.check_box %><%= tag.label %>
			<br>
		<% end %>
	</p>

	<p>
		<%= form.label :project_description, "Detailed description (Markdown-enabled)" %>
		<%= form.text_area :project_description, cols: 40, rows: 10 %>
	</p>

	<p>
		<%= form.label :youtube_url, "YouTube URL" %>
		<%= form.text_field :youtube_url, placeholder: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", type: "url" %>
	</p>

	<p>
		<%= form.label :download_url, "Download link" %>
		<%= form.text_field :download_url, placeholder: "http://awesometeam.github.io/ourproject/download", type: "url" %>
	</p>

	<p>
		<%= form.label :website_url, "Website URL" %>
		<%= form.text_field :website_url, placeholder: "http://awesometeam.github.io/ourproject", type: "url" %>
	</p>

  <p>
    <%= form.label :team_photo_url, "Team Photo URL" %>
    <%= form.text_field :team_photo_url, placeholder: "https://i.imgur.com/something.png", type: "url" %>
  </p>

	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/volunteer/teams/index.html.erb
<h1>Teams</h1>

<p>
  Here are the teams at your event. From here, you can edit them, delete them,
  or add a team photo for one.
</p>

<table>
  <tr>
    <th>
      Name
    </th>
    <th>
      Team Code
    </th>
    <th>
      Users
    </th>
    <th>
      Actions
    </th>
  </tr>
  <% @teams.each do |team| %>
    <tr>
      <td>
        <%= team.name %>
      </td>
      <td>
        <%= team.code %>
      </td>
      <td>
        <% team.users.each do |user| %>
          <%= link_to user.name, user %>
        <% end %>
      </td>
      <td>
        <%= link_to "Edit", edit_volunteer_team_path(team) %>
      </td>
    </tr>
  <% end %>
</table>