config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'
  root 'main#index'

  get '/filter' => 'main#filter'
  get '/oauth/s5' => 'main#s5'
  get '/logout' => 'users#logout'
  get '/hall_of_fame' => 'main#hall_of_fame'

  get '/error' => 'main#intentional_error'

  scope 'teams', as: 'teams' do
    get '/mine' => 'teams#code'
    post '/mine' => 'teams#user_update'
    get '/join' => 'teams#join'
    get '/join/:code' => 'teams#join_link', as: 'join_link'
    post '/join' => 'teams#join_team'
    get '/leave' => 'teams#leave'
    post '/project' => 'teams#save_project'
  end

  get '/teams/batch/:batch_id/event/:id' => 'teams#event', as: 'event'
  get '/teams/batch/:id' => 'teams#batch', as: 'batch'

  scope 'login', as: 'login' do
    get '/' => 'users#login'
    get '/s5' => 'users#s5_login'
    post '/' => 'users#post_login'
    get '/manual' => 'main#manual_login', as: 'manual'
    post '/manual' => 'main#manual_login'
  end

  scope 'register', as: 'register' do
    get '/' => 'users#register'
    post '/' => 'users#post_register'
  end

  scope 'api', as: 'api' do
    get '/me' => 'users#api_me'
    get '/exchange' => 'main#exchange_token'
    post '/slack/:id' => 'main#slack_hook', as: 'slack_hook'
  end

  scope 'legacy', as: 'legacy' do
    get '/' => 'main#legacy'
    get '/oauth' => 'main#legacy_oauth'
  end

  namespace :judge do
    root 'main#index'
    resources :awards
    post '/awards/:id' => 'awards#update'
  end

  namespace :volunteer do
    root 'main#index'
    resources :awards
    resources :teams
    post '/awards/:id' => 'awards#update'
  end

  namespace :admin do
    root 'main#index'
    get '/set_batch/:id' => 'main#set_batch', as: 'set_batch'
    get '/set_event/:id' => 'main#set_event', as: 'set_event'
    get '/event' => 'main#event', as: 'event'
    get '/batch' => 'main#batch', as: 'batch'
    get '/awards' => 'main#awards', as: 'awards'
    get '/awards/seed' => 'main#seed_awards', as: 'seed_awards'
    get '/scramble' => 'main#scramble', as: 'scramble'
    post '/inject' => 'main#inject', as: 'inject'
  end

  namespace :integration do
    root 'main#index'
    get '/slack' => 'slack#index'
    patch '/slack' => 'slack#update_token'
  end

  resources :teams
  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @title %> - CodeDay Showcase</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
	<% if Rails.env.development? %>
		<script src="http://localhost:8080/socket.io/socket.io.js"></script>
	<% else %>
		<script src="https://codeday-teams-socket.herokuapp.com/socket.io/socket.io.js"></script>
	<% end %>

	<!-- <script src="https://cdn.raygun.io/raygun4js/raygun.min.js"></script> -->

	<% @open_graph.each do |prop, value| %>
		<meta property="og:<%= prop %>" content="<%= value %>"/>
	<% end %>

	<% @twitter_card.each do |prop, value| %>
		<meta property="twitter:<%= prop %>" content="<%= value %>"/>
	<% end %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
	<%= csrf_meta_tags %>
	<script type="text/javascript">
    !function(a,b,c,d,e,f,g,h){a.RaygunObject=e,a[e]=a[e]||function(){
    (a[e].o=a[e].o||[]).push(arguments)},f=b.createElement(c),g=b.getElementsByTagName(c)[0],
    f.async=1,f.src=d,g.parentNode.insertBefore(f,g),h=a.onerror,a.onerror=function(b,c,d,f,g){
    h&&h(b,c,d,f,g),g||(g=new Error(b)),a[e].q=a[e].q||[],a[e].q.push({
    e:g})}}(window,document,"script","//cdn.raygun.io/raygun4js/raygun.min.js","rg4js");
	</script>
</head>
<body class="<%= @extra_body_class %>" data-no-turbolink>
	<div class="material-wrapper">
		<header>
			<!-- <codeday-logo></codeday-logo> -->
			<nav>
				<%= link_to "CodeDay Showcase", root_path %>
				<nav-right>
					<% unless current_user %>
						<%= link_to "Login", login_s5_path, { :"data-no-instant" => true } %>
					<% else %>
						<% if current_user_team %>
							<%= link_to "My Team", teams_mine_path %>
						<% else %>
							<%= link_to "Join Team", teams_join_path %>
						<% end %>

						<% if current_user.judge %>
							<%= link_to "Judge", judge_root_path %>
						<% end %>

						<% if current_user.volunteer %>
							<%= link_to "Volunteer", volunteer_teams_path %>
						<% end %>

						<% if current_user.admin %>
							<%= link_to "Admin", admin_root_path %>
						<% end %>

						<%= link_to current_user.username, current_user %>
						<%= link_to "Logout", logout_path, { :"data-no-instant" => true } %>
					<% end %>
				</nav-right>
			</nav>
		</header>
	</div>
	<div class="content">
		<% if flash[:error] %>
			<div class="alert-error">
				<b>Error:</b><br>
				<%= flash[:error].html_safe %>
			</div>
		<% end %>

		<% if flash[:message] %>
			<div class="alert-message">
				<%= flash[:message].html_safe %>
			</div>
		<% end %>
		<%= yield %>
	</div>
	<footer>
		&copy; <%= link_to "StudentRND", "https://srnd.org" %> 2015-2017
		<% if Rails.env == "development" %>
			- <%= link_to "Manual Login", login_manual_path %>
		<% end %>
	</footer>
	<script type="text/javascript" data-no-instant>
	  rg4js('apiKey', 'yL1sJRi3GiP36tEKHqiE9Q==');
	  rg4js('enablePulse', true);
	  rg4js('enableCrashReporting', false);

		<% if current_user %>
			rg4js('setUser', {
				identifier: "<%= current_user.id %>",
				isAnonymous: false,
				fullName: "<%= j current_user.name %>",
				email: "<%= j current_user.email %>"
			});
		<% end %>

		InstantClick.on('change', function() {
			if(Raygun) Raygun.trackEvent('pageView', { path: location.pathname + location.search });
		});
	</script>
	<script data-no-instant>InstantClick.init();</script>
</body>
</html>